## Chap4 numpy套件(numeric python)

為什麼需要numpy?
 * numpy由c撰寫，速度快python 10~1000倍以上
 * numpy儲存結果較正確，python數字儲存不正確
 * numpy節省記憶儲存空間
 * numpy的向量(矩陣計算)速度快
 * numpy的取值方便

In [1]:
a_list=[41,35,86,95,22]
print(a_list*5)

[41, 35, 86, 95, 22, 41, 35, 86, 95, 22, 41, 35, 86, 95, 22, 41, 35, 86, 95, 22, 41, 35, 86, 95, 22]


In [2]:
#numpy套件的ndarray型態,提供eLemunt-wise的操作
import numpy as np
a=np.array([14,39,87,46,58])
print(a*8)

[112 312 696 368 464]


In [8]:
a=np.array([6,7,8,9,10])
print(type(a))
print(a.shape) #ndarray的形狀
print(a.dtype) #資料的型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(5,)
int32
1


In [15]:
import numpy as np
z=np.zeros(5)
print(z)
print(np.empty((3,4))) #產生3X4的二維陣列
print(np.arange(10)) #產生0~9的陣列

[0. 0. 0. 0. 0.]
[[1.22055255e-311 1.22055255e-311 1.22055255e-311 1.22055255e-311]
 [1.22055362e-311 1.22055362e-311 1.22055362e-311 1.22055255e-311]
 [1.22055255e-311 1.22055255e-311 1.22055255e-311 1.22055362e-311]]
[0 1 2 3 4 5 6 7 8 9]


## ndarray的進階操作

In [27]:
my_array=np.arange(8)
print(my_array)
print(my_array[5])
print(my_array[3:7])

[0 1 2 3 4 5 6 7]
5
[3 4 5 6]


## 二維資料取值

In [30]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])
print(my_2d_array[:,1])
print(my_2d_array[1,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [42]:
my_array=np.arange(0,10)
print(my_array)
print(my_array.shape)
my_2d_array=my_array.reshape(5,2)
print(my_2d_array)
print(np.arange(0,50).reshape(10,5))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


## numpy的空值

In [44]:
b=np.array([16, 35, 95, 87, np.nan]) #nan=空值
print(b)

[16. 35. 95. 87. nan]
